#!/usr/bin/env python3
"""
AutoBlogger Environment Setup Script
Creates .env file with your API keys
"""

import os

def create_env_file():
    """Create .env file with the provided API key"""
    
    env_content = """# AutoBlogger Environment Variables
# Generated by setup_env.py

# AI Provider API Keys
GEMINI_API_KEY=your_gemini_key_here
UNSPLASH_ACCESS_KEY=your_unsplash_key_here

# Application Settings
LOG_LEVEL=INFO
ENVIRONMENT=development
DEBUG=true

# Database (for future use)
DATABASE_URL=sqlite:///autoblogger.db

# Web Interface
WEB_HOST=0.0.0.0
WEB_PORT=3500
WEB_DEBUG=true
"""
    
    try:
        with open('.env', 'w') as f:
            f.write(env_content)
        print("âœ… .env file created successfully!")
        print("ðŸ”‘ Edit .env to add your real Gemini and Unsplash keys")
        return True
    except Exception as e:
        print(f"âŒ Error creating .env file: {e}")
        return False

def test_api_key():
    """Test if the Gemini API key works"""
    try:
        import google.generativeai as genai
        import os
        from dotenv import load_dotenv
        
        # Load environment variables
        load_dotenv()
        
        api_key = os.getenv('GEMINI_API_KEY')
        if not api_key:
            print("âŒ No API key found in .env file")
            return False
            
        # Configure Gemini
        genai.configure(api_key=api_key)
        
        # Test with a simple request
        model = genai.GenerativeModel('gemini-pro')
        response = model.generate_content("Hello, this is a test. Respond with 'API key working!'")
        
        if response and response.text:
            print("âœ… Gemini API key is working!")
            print(f"ðŸ¤– Test response: {response.text}")
            return True
        else:
            print("âŒ API key test failed - no response")
            return False
            
    except Exception as e:
        print(f"âŒ API key test failed: {e}")
        return False

if __name__ == "__main__":
    print("ðŸš€ Setting up AutoBlogger environment...")
    
    # Create .env file
    if create_env_file():
        print("\nðŸ§ª Testing API key...")
        test_api_key()
        
        print("\nðŸŽ‰ Setup complete!")
        print("ðŸ“‹ Next steps:")
        print("1. Install dependencies: pip install -r requirements.txt")
        print("2. Start the web interface: python start_web.py")
        print("3. Open http://localhost:3500 in your browser")
    else:
        print("âŒ Setup failed. Please check the error messages above.")

