@echo off
echo ðŸš€ Setting up AutoBlogger environment...

echo # AutoBlogger Environment Variables > .env
echo # Generated by setup_env.bat >> .env
echo. >> .env
echo # AI Provider API Keys >> .env
echo GEMINI_API_KEY=your_gemini_key_here >> .env
echo UNSPLASH_ACCESS_KEY=your_unsplash_key_here >> .env
echo. >> .env
echo # Application Settings >> .env
echo LOG_LEVEL=INFO >> .env
echo ENVIRONMENT=development >> .env
echo DEBUG=true >> .env
echo. >> .env
echo # Database (for future use) >> .env
echo DATABASE_URL=sqlite:///autoblogger.db >> .env
echo. >> .env
echo # Web Interface >> .env
echo WEB_HOST=0.0.0.0 >> .env
echo WEB_PORT=3500 >> .env
echo WEB_DEBUG=true >> .env

echo âœ… .env file created successfully!
echo ðŸ”‘ Edit .env to add your real Gemini and Unsplash keys
echo.
echo ðŸŽ‰ Setup complete!
echo ðŸ“‹ Next steps:
echo 1. Install dependencies: pip install -r requirements.txt
echo 2. Start the web interface: python start_web.py
echo 3. Open http://localhost:3500 in your browser
echo.
pause

